import type { Metadata } from "next";
import { Nunito, Poppins } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/Footer";
import Providers from "@/components/Providers";
import StyledComponentsRegistry from "@/lib/registry";
import Header from "@/components/Header";

const nunito = Nunito({
	weight: ["400", "500", "600", "700", "900"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${nunito.className}  antialiased`}>
				<Providers>
					<StyledComponentsRegistry>
						{children}
					</StyledComponentsRegistry>
				</Providers>
				<Toaster />
			</body>
		</html>
	);
}
