spring.application.name=framework-application

spring.datasource.url=jdbc:sqlserver://localhost:1444;database=AptFeeManage;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=KyThuatPhanMem@123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

jwt.valid-duration=10
jwt.refresh-duration=20
jwt.signerKey=5FA4j2OJt+lQRF5PXDNFHyk5ecqeUlH+PFcjJrz5zxHowrVlcVHpC2s7htYkdMbf
jwt.keys.list.key0=YIRe1vyyCupkMSzc49RfKZRfjSjZlqBQNDWknazIu2OgO5rX1no9y7cprF9EOq6g/uYMhKPw87xN6VGqoRIaCkKLWCUirsxdeedO34DQn/Y=
jwt.keys.list.key1=Zn7f7Uf4OBbzrAm1TPgiTDb5UXC6BTCjVy7+YBtdgJn/6P9KhIECQAJTjpePdakMyQW7hosByQghkx5c8rZ2Dy8v74lcGYlCXYE8C5Wtuyc=
jwt.keys.list.key2=m3X6+3ki+60xTWwq7W2Ud6IQ4txlAEnqjYxeC0XnLIGQOHRPyAMiK9ke4wZkh91DNSRvuwwY3Q75c1+YnZtlpRGFK7np3T++Kq6EHdPJCWI=
jwt.keys.list.key3=LrY/mWRA8yMCXrsWokC1NTWAFnf5LAk/EhY7IyWcWMdingIzpNXxcRS7AGJRQmwbFcoSOSVlIKIaHfOPGs9mSgsf3LL/7YZha3Npefzq3b4=